import { NextRequest,NextResponse } from 'next/server';import { z } from 'zod';import { getPlayer,mutatePlayer } from '@/lib/server-store';import { BUS_ROUTE,FOODS,SLEEP_OPTIONS,SPOTS } from '@/content/game';import { advanceGameTime,attractionStatus,clamp,shouldUnlockBagan } from '@/lib/rules';import type { GameplayEventType, PlayerSave } from '@/lib/types';
import { consumeQuestEvent } from '@/content/day-one';import { identityForRequest,publicIdentity } from '@/lib/auth';
import { activityById, LOCATIONS } from '@/content/locations';
import { checkpointNear, isSafeWorldPosition } from '@/content/world';
import { AVATAR_ITEMS, AVATAR_SLOTS, avatarItem, validAvatarLoadout } from '@/content/avatar';
export const dynamic='force-dynamic';
const bodySchema=z.object({action:z.enum(['checkpoint','enterLocation','leaveLocation','activity','orderFood','interact','photo','sleep','travel','avatarStart','avatarEquip','avatarBuy','completeDay','dev']),target:z.string().max(80).optional(),locationId:z.string().max(80).optional(),foodId:z.string().max(80).optional(),requestId:z.string().uuid().optional(),value:z.number().finite().optional(),facingScore:z.number().min(-1).max(1).optional(),position:z.tuple([z.number(),z.number(),z.number()]).optional(),loadout:z.record(z.enum(AVATAR_SLOTS),z.string().max(80).nullable()).optional()}).strict();
const addOnce=(xs:string[],x:string)=>xs.includes(x)?xs:[...xs,x];
function emit(player:PlayerSave,type:GameplayEventType,targetId:string,metadata?:Record<string,string|number|boolean>){return consumeQuestEvent(player,{id:crypto.randomUUID(),type,targetId,at:new Date().toISOString(),metadata});}

function finalize(before:PlayerSave,next:PlayerSave){const quests=[...(next.completedQuests??[])];if(next.foods.length&&!quests.includes('first_taste'))quests.push('first_taste');if(next.photos.length&&!quests.includes('golden_frame'))quests.push('golden_frame');if(next.discoveries.includes('market')&&next.discoveries.includes('viewpoint')&&!quests.includes('city_threads'))quests.push('city_threads');const evaluated={...next,completedQuests:quests};const unlocked=!before.baganUnlocked&&shouldUnlockBagan(evaluated);return {...evaluated,baganUnlocked:evaluated.baganUnlocked||unlocked,timeline:unlocked?[...evaluated.timeline,{at:new Date().toISOString(),day:evaluated.day,text:'Bagan unlocked — a new road awaits!'}]:evaluated.timeline};}
export async function GET(req:NextRequest){const identity=await identityForRequest(req);if(!identity)return NextResponse.json({error:'Journey session required'},{status:401});return NextResponse.json({player:await getPlayer(identity.playerId),identity:publicIdentity(identity),serverNow:new Date().toISOString()});}
export async function POST(req:NextRequest){const identity=await identityForRequest(req);if(!identity)return NextResponse.json({error:'Journey session required'},{status:401});const parsed=bodySchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Invalid request'},{status:400});const b=parsed.data;try{const player=await mutatePlayer(identity.playerId,p=>finalize(p,apply(p,b)));return NextResponse.json({player,identity:publicIdentity(identity),serverNow:new Date().toISOString()});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Action failed'},{status:409})}}
function apply(p:PlayerSave,b:z.infer<typeof bodySchema>):PlayerSave{if(b.action!=='dev'&&p.majorState!=='EXPLORING')throw new Error('Another persistent action is active');const now=new Date();
 if(b.action==='enterLocation'){const location=LOCATIONS.find(x=>x.id===b.locationId);if(!location)throw new Error('Unknown location');if(location.id==='market'&&!p.discoveries.includes('market_revealed'))throw new Error('Ask for a market recommendation first');if(location.id==='shwedagon'&&!p.discoveries.includes('landmark_revealed'))throw new Error('Ask a market seller about Yangon first');if(location.id==='viewpoint'&&!p.discoveries.includes('viewpoint_revealed'))throw new Error('Find a clue to the viewpoint first');if(p.locationContext!=='WORLD'&&p.locationContext!==location.type)throw new Error('Leave the current location first');const spot=SPOTS.find(x=>x.id===location.id);if(!spot||Math.hypot(spot.position[0]-p.position[0],spot.position[2]-p.position[2])>6)throw new Error('Move closer to the entrance');const arrival=location.id==='tea_shop'?'tea_shop_entered':`${location.id}_entered`;const fresh=!p.discoveries.includes(arrival);const entered={...p,locationContext:location.type,discoveries:addOnce(addOnce(p.discoveries,arrival),`place:${location.id}`),timeline:fresh?[...p.timeline,{at:now.toISOString(),day:p.day,text:`Entered ${location.name}`}]:p.timeline};const withEntry=emit(entered,'LOCATION_ENTERED',location.id);return location.id==='viewpoint'?emit({...withEntry,discoveries:addOnce(withEntry.discoveries,'viewpoint')},'LOCATION_DISCOVERED','viewpoint'):withEntry}
 if(b.action==='leaveLocation'){const location=LOCATIONS.find(x=>x.type===p.locationContext);if(!location)throw new Error('Not currently inside a location');const spot=SPOTS.find(x=>x.id===location.id)!;const position:[number,number,number]=[spot.position[0],1.1,spot.position[2]];return {...p,locationContext:'WORLD',position,lastSafePosition:position}}
 if(b.action==='avatarStart'){const loadout=validAvatarLoadout(b.loadout);if(Object.values(loadout).some(id=>id&&!p.avatarInventory.includes(id)))throw new Error('Choose starter items only');return {...p,avatarLoadout:loadout,avatarCreated:true,timeline:[...p.timeline,{at:now.toISOString(),day:p.day,text:'Created a traveler appearance'}]}}
 if(b.action==='avatarEquip'){const item=avatarItem(b.target);if(!item||!p.avatarInventory.includes(item.id))throw new Error('You do not own this item');return {...p,avatarLoadout:{...p.avatarLoadout,[item.slot]:item.id}}}
 if(b.action==='avatarBuy'){if(!b.requestId)throw new Error('Missing purchase request');if(p.processedRequests.includes(b.requestId))return p;const item=AVATAR_ITEMS.find(x=>x.id===b.target&&x.unlockType==='MARKET');if(!item)throw new Error('This cosmetic is not sold here');if(p.avatarInventory.includes(item.id))throw new Error('You already own this item');if(p.mmk<item.price)throw new Error('Not enough MMK');return {...p,mmk:p.mmk-item.price,avatarInventory:[...p.avatarInventory,item.id],processedRequests:[...p.processedRequests.slice(-49),b.requestId],timeline:[...p.timeline,{at:now.toISOString(),day:p.day,text:`Bought ${item.name} (-${item.price} MMK)`}]}}
 if(b.action==='checkpoint'){if(!b.position||!isSafeWorldPosition(b.position))return p;const t=advanceGameTime(p.day,p.gameMinutes,1),checkpoint=checkpointNear(b.position)??p.currentCheckpoint;return {...p,position:b.position,lastSafePosition:b.position,currentCheckpoint:checkpoint,day:t.day,gameMinutes:t.minutes,energy:clamp(p.energy-.2,0,100)}}
 if(b.action==='interact'){const spot=SPOTS.find(s=>s.id===b.target);if(!spot)throw new Error('Unknown interaction');if(spot.kind==='attraction'&&attractionStatus(p.gameMinutes)==='CLOSED')throw new Error('The gardens are closed (game hours 06:00–21:00)');const fresh=!p.discoveries.includes(spot.id),reward=fresh?(spot.kind==='attraction'?2600:800):0;return {...p,discoveries:addOnce(p.discoveries,spot.id),talkedTo:spot.kind==='npc'||spot.id==='hotel'?addOnce(p.talkedTo,spot.id):p.talkedTo,mmk:p.mmk+reward,energy:spot.kind==='attraction'?clamp(p.energy-8,0,100):p.energy,timeline:fresh?[...p.timeline,{at:now.toISOString(),day:p.day,text:`Discovered ${spot.name} (+${reward} MMK)`}]:p.timeline}}
 if(b.action==='orderFood'){if(!b.requestId)throw new Error('Missing purchase request');if(p.processedRequests.includes(b.requestId))return p;const activity=LOCATIONS.find(x=>x.id==='tea_shop')?.activities.map(activityById).find(x=>x?.foodId===b.foodId);if(!activity)throw new Error('Invalid food');if(p.locationContext!=='TEA_SHOP')throw new Error('Enter the Tea Shop before ordering');if(p.energy>=100)throw new Error('Energy is already full');if(p.mmk<(activity.mmkCost??0))throw new Error(`Not enough MMK. You need ${(activity.mmkCost??0).toLocaleString()} MMK to order ${activity.name}.`);const fresh=!p.foods.includes(activity.foodId!),t=advanceGameTime(p.day,p.gameMinutes,activity.gameMinutes);return emit({...p,processedRequests:[...p.processedRequests.slice(-49),b.requestId],day:t.day,gameMinutes:t.minutes,mmk:p.mmk-(activity.mmkCost??0),energy:clamp(p.energy+(activity.energyRestore??0),0,100),foods:addOnce(p.foods,activity.foodId!),discoveries:addOnce(p.discoveries,activity.discoveryId!),timeline:[...p.timeline,{at:now.toISOString(),day:t.day,text:`Ate ${activity.name} at Morning Star Tea Shop (-${activity.mmkCost} MMK, +${activity.energyRestore} energy, +${activity.gameMinutes} minutes)${fresh?' · New food added to Journal':''}`}]},'FOOD_EATEN',activity.foodId!)}
 if(b.action==='activity'){if(b.requestId&&p.processedRequests.includes(b.requestId))return p;const activity=activityById(b.target??'');if(!activity||activity.foodId)throw new Error('Unknown activity');const location=LOCATIONS.find(x=>x.id===activity.locationId);if(!location||p.locationContext!==location.type)throw new Error(`Enter ${location?.name??'the location'} first`);const completed=activity.discoveryId?p.discoveries.includes(activity.discoveryId):activity.inventoryItem?p.inventory.includes(activity.inventoryItem):false;if(completed&&!activity.repeatable)throw new Error('This discovery is already complete');if(p.mmk<(activity.mmkCost??0))throw new Error('Not enough MMK');if(p.energy<(activity.energyCost??0)||p.energy<(activity.requirements?.minimumEnergy??0))throw new Error('Not enough energy');const first=!completed,t=advanceGameTime(p.day,p.gameMinutes,activity.gameMinutes);const discovery=activity.discoveryId;let next:PlayerSave={...p,processedRequests:b.requestId?[...p.processedRequests.slice(-49),b.requestId]:p.processedRequests,day:t.day,gameMinutes:t.minutes,mmk:p.mmk-(activity.mmkCost??0)+(first?(activity.mmkReward??0):0),energy:clamp(p.energy-(activity.energyCost??0)+(activity.energyRestore??0),0,100),discoveries:discovery?addOnce(addOnce(p.discoveries,discovery),activity.discoveryId!):p.discoveries,talkedTo:activity.id==='meet_tea_owner'?addOnce(p.talkedTo,'tea_owner'):activity.id==='meet_market_seller'?addOnce(p.talkedTo,'market_seller'):p.talkedTo,inventory:activity.inventoryItem?addOnce(p.inventory,activity.inventoryItem):p.inventory,timeline:[...p.timeline,{at:now.toISOString(),day:t.day,text:`${activity.name}: ${activity.mmkCost?`-${activity.mmkCost} MMK · `:''}${activity.energyRestore?`+${activity.energyRestore} energy · `:''}+${activity.gameMinutes} minutes${first&&activity.discoveryId?' · new discovery':''}`} ]};next=emit(next,'ACTIVITY_COMPLETED',activity.id);if(activity.id==='landmark_recommendation')next=emit(next,'LOCATION_REVEALED','shwedagon');if(activity.id==='market_recommendation')next=emit(next,'LOCATION_REVEALED','market');if(activity.id==='landmark_visit')next=emit(next,'LOCATION_DISCOVERED','shwedagon');return next}
 if(b.action==='photo'){const challenge=b.target;if(!['landmark_photo','viewpoint_photo'].includes(challenge??''))throw new Error('No active photo challenge');const expected=challenge==='landmark_photo'?{objective:'PHOTOGRAPH_LANDMARK',location:'shwedagon'}:{objective:'TAKE_VIEWPOINT_PHOTO',location:'viewpoint'};if(p.activeObjectiveId!==expected.objective)throw new Error('That photo challenge is not active');if(p.locationContext!==LOCATIONS.find(x=>x.id===expected.location)?.type)throw new Error('Move to the correct location first');if((b.facingScore??0)<.35)throw new Error('Turn the camera toward the subject');if(p.energy<3)throw new Error('Too exhausted to focus the camera');const fresh=!p.photos.includes(challenge!);const sunset=p.gameMinutes>=1020&&p.gameMinutes<1200;let next:PlayerSave={...p,photos:addOnce(p.photos,challenge!),photoMetadata:fresh?[...p.photoMetadata,{id:crypto.randomUUID(),challengeId:challenge!,locationId:expected.location,day:p.day,gameMinutes:p.gameMinutes,position:p.position,facingScore:b.facingScore!,sunset,capturedAt:now.toISOString()}]:p.photoMetadata,discoveries:sunset&&challenge==='viewpoint_photo'?addOnce(p.discoveries,'sunset_shot'):p.discoveries,energy:clamp(p.energy-3,0,100),timeline:fresh?[...p.timeline,{at:now.toISOString(),day:p.day,text:`Captured ${challenge==='landmark_photo'?'Landmark Photograph':'Hidden Viewpoint'}${sunset&&challenge==='viewpoint_photo'?' · Sunset Shot':''}`}]:p.timeline};next=emit(next,'PHOTO_TAKEN',challenge!);if(challenge==='landmark_photo')next={...next,discoveries:addOnce(next.discoveries,'viewpoint_revealed')};return next}
 if(b.action==='completeDay'){if(p.locationContext!=='HOTEL'||p.activeObjectiveId!=='RETURN_TO_GUEST_HOUSE')throw new Error('Complete the Day 1 journey first');let next=emit({...p,dayOneCompleted:true,completedObjectives:addOnce(p.completedObjectives,'RETURN_TO_GUEST_HOUSE'),timeline:[...p.timeline,{at:now.toISOString(),day:p.day,text:'Completed Yangon Day 1'}]},'DAY_COMPLETED','YANGON_DAY_1');return next}
 if(b.action==='sleep'){const option=SLEEP_OPTIONS.find(o=>o.hours===b.value);if(!option)throw new Error('Invalid sleep duration');const scale=Number(process.env.DEV_TIMER_SCALE??1);const completes=new Date(now.getTime()+option.hours*6*60000*scale);const untilNextMorning=(1440-p.gameMinutes)+480;return {...p,majorState:'SLEEPING',activeAction:{id:crypto.randomUUID(),kind:'SLEEP',startedAt:now.toISOString(),completesAt:completes.toISOString(),gameMinutes:untilNextMorning,energyRecovery:option.recovery}}}
 if(b.action==='travel'){if(!p.baganUnlocked)throw new Error('Document more of Yangon first');if(p.mmk<BUS_ROUTE.price)throw new Error('Not enough MMK');const scale=Number(process.env.DEV_TIMER_SCALE??1),completes=new Date(now.getTime()+BUS_ROUTE.realMinutes*60000*scale);return {...p,mmk:p.mmk-BUS_ROUTE.price,majorState:'TRAVELLING',activeAction:{id:crypto.randomUUID(),kind:'TRAVEL',startedAt:now.toISOString(),completesAt:completes.toISOString(),gameMinutes:BUS_ROUTE.gameHours*60,energyRecovery:0,destination:'BAGAN'},timeline:[...p.timeline,{at:now.toISOString(),day:p.day,text:'Departed Yangon for Bagan'}]}}
 if(b.action==='dev'){if(process.env.NODE_ENV==='production')throw new Error('Development tools disabled');if(b.target==='completeTimer'&&p.activeAction)return {...p,activeAction:{...p.activeAction,completesAt:new Date(0).toISOString()}};if(b.target==='unlock')return {...p,baganUnlocked:true};if(b.target==='mmk')return {...p,mmk:Math.max(0,p.mmk+(b.value??5000))};if(b.target==='energy')return {...p,energy:clamp(p.energy+(b.value??10),0,100)};if(b.target==='time')return {...p,gameMinutes:clamp(b.value??480,0,1439)};throw new Error('Unknown dev command')}
 return p}
