import { NextRequest,NextResponse } from 'next/server';import { z } from 'zod';import { getPlayer,mutatePlayer } from '@/lib/server-store';import { BUS_ROUTE,FOODS,SLEEP_OPTIONS,SPOTS } from '@/content/game';import { advanceGameTime,attractionStatus,clamp,shouldUnlockBagan } from '@/lib/rules';import type { GameplayEventType, PlayerSave } from '@/lib/types';
import { applyPlayerAction } from '@/lib/player-actions';import { identityForRequest,publicIdentity } from '@/lib/auth';
import { activityById, LOCATIONS } from '@/content/locations';
import { checkpointNear, isSafeWorldPosition } from '@/content/world';
import { AVATAR_ITEMS, AVATAR_SLOTS, avatarItem, validAvatarLoadout } from '@/content/avatar';
export const dynamic='force-dynamic';
const bodySchema=z.object({action:z.enum(['checkpoint','enterLocation','leaveLocation','activity','luggage','orderFood','interact','photo','sleep','travel','avatarStart','avatarEquip','avatarBuy','completeDay','dev']),target:z.string().max(80).optional(),locationId:z.string().max(80).optional(),foodId:z.string().max(80).optional(),destinationId:z.string().max(80).optional(),transportOptionId:z.string().max(80).optional(),requestId:z.string().uuid().optional(),value:z.number().finite().optional(),facingScore:z.number().min(-1).max(1).optional(),position:z.tuple([z.number(),z.number(),z.number()]).optional(),loadout:z.record(z.enum(AVATAR_SLOTS),z.string().max(80).nullable()).optional()}).strict();
function finalize(before:PlayerSave,next:PlayerSave){const quests=[...(next.completedQuests??[])];if(next.foods.length&&!quests.includes('first_taste'))quests.push('first_taste');if(next.photos.length&&!quests.includes('golden_frame'))quests.push('golden_frame');if(next.discoveries.includes('market')&&next.discoveries.includes('viewpoint')&&!quests.includes('city_threads'))quests.push('city_threads');const evaluated={...next,completedQuests:quests};const unlocked=!before.baganUnlocked&&shouldUnlockBagan(evaluated);return {...evaluated,baganUnlocked:evaluated.baganUnlocked||unlocked,timeline:unlocked?[...evaluated.timeline,{at:new Date().toISOString(),day:evaluated.day,text:'Bagan unlocked — a new road awaits!'}]:evaluated.timeline};}
export async function GET(req:NextRequest){const identity=await identityForRequest(req);if(!identity)return NextResponse.json({error:'Journey session required'},{status:401});return NextResponse.json({player:await getPlayer(identity.playerId),identity:publicIdentity(identity),serverNow:new Date().toISOString()});}
export async function POST(req:NextRequest){const identity=await identityForRequest(req);if(!identity)return NextResponse.json({error:'Journey session required'},{status:401});const parsed=bodySchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Invalid request'},{status:400});const b=parsed.data;try{const player=await mutatePlayer(identity.playerId,p=>finalize(p,applyPlayerAction(p,b)));return NextResponse.json({player,identity:publicIdentity(identity),serverNow:new Date().toISOString()});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Action failed'},{status:409})}}
