import {describe,expect,it} from 'vitest';
import {applyPlayerAction} from '../src/lib/player-actions';
import {newPlayer,resolveAction} from '../src/lib/rules';
import {BUS_ROUTE} from '../src/content/game';
const request=()=>crypto.randomUUID();
const ready=()=>{const p=newPlayer('ready');p.avatarCreated=true;p.locationContext='BUS_STATION';p.baganUnlocked=true;p.dayOneCompleted=true;p.luggageState='CARRYING';p.mmk=15000;p.activeObjectiveId='BUY_BAGAN_TICKET';return p};
describe('luggage and authoritative travel actions',()=>{
 it('stores luggage, advances its quest, persists, and makes duplicate storage harmless',()=>{const p=newPlayer('bag');p.locationContext='HOTEL';p.discoveries=['hotel_checked_in'];p.activeObjectiveId='LEAVE_YOUR_BAG';const id=request();const stored=applyPlayerAction(p,{action:'luggage',target:'store',requestId:id});expect(stored.luggageState).toBe('STORED_AT_GUEST_HOUSE');expect(stored.activeObjectiveId).toBe('VISIT_TEA_SHOP');expect(applyPlayerAction(stored,{action:'luggage',target:'store',requestId:id})).toEqual(stored);expect(resolveAction(JSON.parse(JSON.stringify(stored))).luggageState).toBe('STORED_AT_GUEST_HOUSE')});
 it('collects stored luggage and advances preparation',()=>{const p=newPlayer('collect');p.locationContext='HOTEL';p.discoveries=['hotel_checked_in'];p.luggageState='STORED_AT_GUEST_HOUSE';p.activeObjectiveId='COLLECT_YOUR_BAG';const next=applyPlayerAction(p,{action:'luggage',target:'collect',requestId:request()});expect(next.luggageState).toBe('CARRYING');expect(next.activeObjectiveId).toBe('GO_TO_BUS_STATION')});
 it('rejects insufficient funds without changing the save',()=>{const p=ready();p.mmk=BUS_ROUTE.price-1;expect(()=>applyPlayerAction(p,{action:'travel',destinationId:'BAGAN',transportOptionId:BUS_ROUTE.id,requestId:request()})).toThrow('Not enough MMK');expect(p.mmk).toBe(BUS_ROUTE.price-1);expect(p.activeAction).toBeNull()});
 it('deducts once and creates exactly one resumable travel action',()=>{const p=ready(),id=request();const started=applyPlayerAction(p,{action:'travel',destinationId:'BAGAN',transportOptionId:BUS_ROUTE.id,requestId:id});expect(started.mmk).toBe(6000);expect(started.majorState).toBe('TRAVELLING');expect(started.activeAction?.kind).toBe('TRAVEL');expect(started.gameplayEvents.at(-1)?.type).toBe('TRAVEL_STARTED');expect(()=>applyPlayerAction(started,{action:'travel',destinationId:'BAGAN',transportOptionId:BUS_ROUTE.id,requestId:id})).toThrow('Another persistent action is active');const restored=resolveAction(JSON.parse(JSON.stringify(started)),new Date(Date.parse(started.activeAction!.completesAt)-1));expect(restored.majorState).toBe('TRAVELLING');expect(restored.mmk).toBe(6000)});
 it('completes travel exactly once into the Bagan coming-soon destination',()=>{const started=applyPlayerAction(ready(),{action:'travel',destinationId:'BAGAN',transportOptionId:BUS_ROUTE.id,requestId:request()});const done=resolveAction(started,new Date(Date.parse(started.activeAction!.completesAt)+1));expect(done.destination).toBe('BAGAN');expect(done.majorState).toBe('EXPLORING');expect(done.activeAction).toBeNull();expect(resolveAction(done,new Date()).timeline).toHaveLength(done.timeline.length)});
});
