'use client';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Environment } from '@react-three/drei';
import * as THREE from 'three';
import { locationById } from '@/content/locations';

function Person({position,color='#9f553e'}:{position:[number,number,number];color?:string}){return <group position={position}><mesh position-y={.75}><capsuleGeometry args={[.25,.7,5,8]}/><meshStandardMaterial color={color}/></mesh><mesh position-y={1.55}><sphereGeometry args={[.22,12,12]}/><meshStandardMaterial color="#9c6546"/></mesh></group>}
function TeaInterior(){return <><mesh position={[0,1,-3]} receiveShadow><boxGeometry args={[7,2,1]}/><meshStandardMaterial color="#345f53"/></mesh>{[-2,0,2].map(x=><group key={x} position={[x,0,0]}><mesh position-y={.72} castShadow><cylinderGeometry args={[.7,.7,.12,20]}/><meshStandardMaterial color="#815034"/></mesh>{[-.85,.85].map(z=><mesh key={z} position={[0,.35,z]} castShadow><cylinderGeometry args={[.27,.31,.7,12]}/><meshStandardMaterial color={x===0?'#d49b42':'#487a72'}/></mesh>)}<mesh position={[.2,.88,0]}><cylinderGeometry args={[.1,.08,.16,12]}/><meshStandardMaterial color="#efe5cb"/></mesh></group>)}<mesh position={[-1.8,2.15,-2.43]} castShadow><cylinderGeometry args={[.35,.45,.75,16]}/><meshStandardMaterial color="#b9b6a5" metalness={.7}/></mesh><mesh position={[1,2,-2.42]}><boxGeometry args={[2.5,.8,.5]}/><meshPhysicalMaterial color="#d5aa68" transmission={.18} roughness={.25}/></mesh>{[-.7,0,.7].map(x=><mesh key={x} position={[x+1,2,-2.12]}><sphereGeometry args={[.16,12,8]}/><meshStandardMaterial color={x?'#cb704d':'#e6bf52'}/></mesh>)}<Person position={[2.2,1,-2.1]}/><Person position={[-2.3,0,.2]} color="#446f71"/><Person position={[2.2,0,.2]} color="#d18b43"/>{[-2.2,0,2.2].map(x=><group key={x} position={[x,3.8,-.3]}><mesh><cylinderGeometry args={[.35,.55,.35,18]}/><meshStandardMaterial color="#405d51"/></mesh><pointLight position={[0,-.25,0]} color="#ffd38a" intensity={2.2} distance={5}/></group>)}<mesh position={[0,4,-1]} receiveShadow><boxGeometry args={[9,.12,7]}/><meshStandardMaterial color="#6e5942"/></mesh></>}
function GenericInterior({theme}:{theme:string}){const colors:Record<string,string>={market:'#9e493b',hotel:'#315d59',landmark:'#c89b2c',station:'#526b7b'};return <>{[-2.4,0,2.4].map((x,i)=><mesh key={x} position={[x,.7,i%2?0:-1]}><boxGeometry args={[1.7,1.4,1.3]}/><meshStandardMaterial color={colors[theme]??'#795d43'}/></mesh>)}<Person position={[0,0,-2]} color="#b06043"/><Person position={[-2,0,1]} color="#507879"/></>}
function CinematicCamera(){const {camera}=useThree();useFrame(({clock})=>{const x=7+Math.sin(clock.elapsedTime*.16)*.12;camera.position.lerp(new THREE.Vector3(x,4.2,8),.025);camera.lookAt(0,1.2,-1.2)});return null}
function Room({theme}:{theme:string}){return <group>{theme==='tea'?<TeaInterior/>:<GenericInterior theme={theme}/>}<mesh position={[0,-.08,0]} rotation-x={-Math.PI/2} receiveShadow><planeGeometry args={[12,10]}/><meshStandardMaterial color="#8c765a" roughness={.85}/></mesh><mesh position={[0,2.5,-4]} receiveShadow><boxGeometry args={[12,5,.2]}/><meshStandardMaterial color="#e2cda8"/></mesh></group>}
export default function LocationScene({id}:{id:string}){const location=locationById(id);return <Canvas className="location-canvas" shadows camera={{position:[7,4.2,8],fov:47}}><color attach="background" args={['#172b28']}/><fog attach="fog" args={['#172b28',13,25]}/><ambientLight intensity={.75}/><directionalLight position={[4,7,5]} intensity={2.2} castShadow/><Environment preset="apartment"/><CinematicCamera/><Room theme={location?.presentation.theme??'hotel'}/></Canvas>}
