'use client';
import { Canvas, useFrame } from '@react-three/fiber';
import { Environment } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';
import { locationById } from '@/content/locations';

function Person({position,color='#9f553e'}:{position:[number,number,number];color?:string}){return <group position={position}><mesh position-y={.75}><capsuleGeometry args={[.25,.7,5,8]}/><meshStandardMaterial color={color}/></mesh><mesh position-y={1.55}><sphereGeometry args={[.22,12,12]}/><meshStandardMaterial color="#9c6546"/></mesh></group>}
function TeaInterior(){return <><mesh position={[0,1,-3]}><boxGeometry args={[7,2,1]}/><meshStandardMaterial color="#345f53"/></mesh>{[-2,0,2].map(x=><group key={x} position={[x,0,0]}><mesh position-y={.72}><cylinderGeometry args={[.7,.7,.12,20]}/><meshStandardMaterial color="#815034"/></mesh>{[-.85,.85].map(z=><mesh key={z} position={[0,.35,z]}><cylinderGeometry args={[.27,.31,.7,12]}/><meshStandardMaterial color="#d49b42"/></mesh>)}</group>)}<mesh position={[-1.8,2.15,-2.43]}><cylinderGeometry args={[.35,.45,.75,16]}/><meshStandardMaterial color="#b9b6a5" metalness={.7}/></mesh><mesh position={[1,2,-2.42]}><boxGeometry args={[2.5,.8,.5]}/><meshStandardMaterial color="#d5aa68"/></mesh><Person position={[2.2,1,-2.1]}/><Person position={[-2.3,0,.2]} color="#446f71"/><Person position={[2.2,0,.2]} color="#d18b43"/></>}
function GenericInterior({theme}:{theme:string}){const colors:Record<string,string>={market:'#9e493b',hotel:'#315d59',landmark:'#c89b2c',station:'#526b7b'};return <>{[-2.4,0,2.4].map((x,i)=><mesh key={x} position={[x,.7,i%2?0:-1]}><boxGeometry args={[1.7,1.4,1.3]}/><meshStandardMaterial color={colors[theme]??'#795d43'}/></mesh>)}<Person position={[0,0,-2]} color="#b06043"/><Person position={[-2,0,1]} color="#507879"/></>}
function Room({theme}:{theme:string}){const group=useRef<THREE.Group>(null);useFrame(({clock})=>{if(group.current)group.current.rotation.y=Math.sin(clock.elapsedTime*.2)*.025});return <group ref={group}>{theme==='tea'?<TeaInterior/>:<GenericInterior theme={theme}/>}<mesh position={[0,-.08,0]} rotation-x={-Math.PI/2}><planeGeometry args={[12,10]}/><meshStandardMaterial color="#8c765a"/></mesh><mesh position={[0,2.5,-4]}><boxGeometry args={[12,5,.2]}/><meshStandardMaterial color="#e2cda8"/></mesh></group>}
export default function LocationScene({id}:{id:string}){const location=locationById(id);return <Canvas className="location-canvas" shadows camera={{position:[7,4.2,8],fov:47}}><color attach="background" args={['#172b28']}/><ambientLight intensity={1.2}/><directionalLight position={[4,7,5]} intensity={2.2} castShadow/><Environment preset="apartment"/><Room theme={location?.presentation.theme??'hotel'}/></Canvas>}
