'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { PersistentAction } from '@/lib/types';
import { BUS_ROUTE } from '@/content/game';

export type TravelResult='NOT_READY'|'COMPLETED'|'RECONCILED';
const clock=(milliseconds:number)=>{const seconds=Math.max(0,Math.ceil(milliseconds/1000));return `${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};
export default function TravelExperience({action,majorState,onVerify,onOpenJournal,onDevComplete}:{action:PersistentAction;majorState:string;onVerify:(travelId:string)=>Promise<TravelResult>;onOpenJournal:()=>void;onDevComplete:()=>Promise<unknown>|void}){
 const [now,setNow]=useState(Date.now()),[requestStatus,setRequestStatus]=useState<'IDLE'|'REQUESTING'|'RETRYING'|'ERROR'>('IDLE'),[lastResult,setLastResult]=useState('NONE'),[message,setMessage]=useState<string|null>(null);
 const inFlight=useRef<string|null>(null),retryTimer=useRef<number|null>(null),mounted=useRef(true),attempted=useRef(false);
 const started=useMemo(()=>Date.parse(action.startedAt),[action.startedAt]),completes=useMemo(()=>Date.parse(action.completesAt),[action.completesAt]),remaining=completes-now,progress=Math.max(0,Math.min(100,(now-started)/Math.max(1,completes-started)*100));
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),250);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>()=>{mounted.current=false;if(retryTimer.current!==null)window.clearTimeout(retryTimer.current)},[]);
 const reconcile=useCallback(async()=>{if(inFlight.current===action.id)return;inFlight.current=action.id;setRequestStatus(attempted.current?'RETRYING':'REQUESTING');attempted.current=true;setMessage(null);if(process.env.NODE_ENV!=='production')console.info(`[Travel] requesting authoritative completion travelId=${action.id}`);try{const result=await onVerify(action.id);if(!mounted.current)return;setLastResult(result);if(process.env.NODE_ENV!=='production')console.info(`[Travel] completion response received result=${result}`);if(result==='COMPLETED'||result==='RECONCILED'){console.info('[Travel] opening Bagan arrival experience');return}retryTimer.current=window.setTimeout(()=>void reconcile(),750);}catch{if(!mounted.current)return;setRequestStatus('ERROR');setLastResult('NETWORK_ERROR');setMessage('Arrival could not be confirmed. Your journey remains safe; retrying automatically.');retryTimer.current=window.setTimeout(()=>void reconcile(),2000);}finally{inFlight.current=null}},[action.id,onVerify]);
 useEffect(()=>{if(remaining>0)return;if(process.env.NODE_ENV!=='production')console.info(`[Travel] timer reached zero travelId=${action.id}`);void reconcile();return()=>{if(retryTimer.current!==null)window.clearTimeout(retryTimer.current)}},[action.id,remaining<=0,reconcile]);
 return <main className="travel-experience" aria-live="polite"><div className="travel-scene" aria-hidden="true"><div className="travel-window"><i className="sky"/><i className="hills"/><i className="road"/></div><div className="bus-seat"/><div className="travel-bag">🎒</div></div><section className="travel-copy"><div className="eyebrow">ON THE ROAD</div><h1>Yangon → Bagan</h1><p>{BUS_ROUTE.name} · travelling</p><div className="sleep-countdown">{clock(remaining)}</div><p>Expected after ~{BUS_ROUTE.gameHours} game hours</p><div className="sleep-progress"><i style={{width:`${progress}%`}}/></div><small>The display is approximate. Only the server's UTC clock can complete this journey.</small>{message&&<div className="sleep-error" role="alert">{message}</div>}<div className="travel-safe-actions"><button onClick={onOpenJournal}>Journey Journal</button><button disabled={requestStatus==='REQUESTING'||requestStatus==='RETRYING'} onClick={()=>void reconcile()}>{requestStatus==='REQUESTING'||requestStatus==='RETRYING'?'Checking…':'Retry'}</button></div>{process.env.NODE_ENV!=='production'&&<><button className="dev-rest" onClick={()=>void onDevComplete()}>DEV · Complete Travel Now</button><pre className="travel-debug">TRAVEL DEBUG{`\n`}Action: {action.id}{`\n`}Status: {action.status??'ACTIVE'}{`\n`}Major State: {majorState}{`\n`}Origin: YANGON{`\n`}Destination: {action.destination}{`\n`}Remaining: {clock(remaining)}{`\n`}Server completesAt: {action.completesAt}{`\n`}Completion: {requestStatus}{`\n`}Last Result: {lastResult}</pre></>}</section></main>
}
