'use client';
import dynamic from 'next/dynamic';
import { FormEvent, useEffect, useState } from 'react';
import { type Identity, useGame } from '@/store/game';
const Game=dynamic(()=>import('@/components/game/Game'),{ssr:false,loading:()=><Loading/>});
type View='landing'|'register'|'login'|'game';
async function auth(body:Record<string,string>){const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);return j.identity as Identity}
export default function Page(){const identity=useGame(s=>s.identity),setIdentity=useGame(s=>s.setIdentity);const[view,setView]=useState<View>(()=>typeof location!=='undefined'&&new URLSearchParams(location.search).has('register')?'register':'landing'),[checking,setChecking]=useState(true);useEffect(()=>{fetch('/api/auth',{cache:'no-store'}).then(r=>r.json()).then(j=>setIdentity(j.identity)).finally(()=>setChecking(false))},[setIdentity]);if(checking)return <Loading/>;if(view==='game'&&identity)return <Game/>;if(view==='register'||view==='login')return <AccountForm mode={view} onBack={()=>setView('landing')} onSuccess={i=>{setIdentity(i);setView('game')}}/>;return <main className="account-screen"><section className="landing-card"><div className="lotus">✦</div><div className="eyebrow">A TRAVEL-GAME JOURNEY</div><h1>Explore Myanmar</h1><p>Discover Myanmar.<br/>One journey at a time.</p>{identity&&<button className="primary account-button" onClick={()=>setView('game')}>Continue Journey</button>}{!identity&&<button className="secondary account-button" onClick={async()=>{const i=await auth({intent:'guest'});setIdentity(i);setView('game')}}>Play as Guest</button>}<button className="secondary account-button" onClick={()=>setView('register')}>{identity?.type==='GUEST'?'Save My Journey':'Create Account'}</button><small>Already have an account?</small><button className="text-button" onClick={()=>setView('login')}>Sign In</button><p className="privacy-note">Your journey is saved securely and restored when you return.</p></section></main>}
function Loading(){return <main className="splash"><div><div className="lotus">✦</div><h1>Explore Myanmar</h1><div className="spinner"/><p>Preparing your journey…</p></div></main>}
function AccountForm({mode,onBack,onSuccess}:{mode:'register'|'login';onBack:()=>void;onSuccess:(i:Identity)=>void}){const[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);try{onSuccess(await auth({intent:mode,...Object.fromEntries(new FormData(e.currentTarget))}as Record<string,string>))}catch(x){setError(x instanceof Error?x.message:'Please try again.');setBusy(false)}}return <main className="account-screen"><form className="account-card" onSubmit={submit}><button type="button" className="back-button" onClick={onBack}>← Back</button><div className="eyebrow">{mode==='register'?'SAVE YOUR JOURNEY':'WELCOME BACK'}</div><h1>{mode==='register'?'Create account':'Sign in'}</h1><p>{mode==='register'?'Keep this journey and continue it on your next visit.':'Return to the road where you left off.'}</p>{mode==='register'&&<label>Display Name<input name="displayName" minLength={2} maxLength={32} autoComplete="name" required/></label>}<label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" minLength={mode==='register'?10:1} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} required/></label>{mode==='register'&&<label>Confirm Password<input name="confirmPassword" type="password" minLength={10} maxLength={128} autoComplete="new-password" required/></label>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='register'?'Create Account':'Sign In'}</button></form></main>}
