export type AINPC = {
  id: string; name: string; role: string; location: string; personality: string[]; speakingStyle: string;
  knowledgeScopes: string[]; questKnowledge: Record<string, string[]>; discoveryKnowledge: string[];
  suggestedQuestions: string[]; fallbackDialogue: Record<string, string>;
  allowedIntents: Record<string, string[]>;
};

export const AI_NPCS: Record<string, AINPC> = {
  tea_shop_owner: { id: 'tea_shop_owner', name: 'Daw Nwe', role: 'Tea shop owner', location: 'tea_shop', personality: ['friendly', 'welcoming', 'interested in local food'], speakingStyle: 'Warm, conversational, and concise.', knowledgeScopes: ['food', 'tea-shops', 'yangon', 'markets'], questKnowledge: { FIND_MARKET: ['market'] }, discoveryKnowledge: ['market'], suggestedQuestions: ['What should I eat?', 'Where should I visit?', 'Tell me about this place'], fallbackDialogue: { greeting: 'Mingalaba. Sit for a moment—there is always room for one more cup.', food: 'Try mohinga: a comforting rice-noodle soup often enjoyed in the morning.', mohinga: 'Mohinga is a fragrant rice-noodle soup, commonly served with fish broth and crisp garnishes.', visit: 'The neighbourhood market is a lively next stop. Follow the road east from the tea shop.', yangon: 'Yangon is best met slowly—through its tea shops, markets, shaded streets, and golden skyline.', quest: 'If you are lost, begin with the market east of here.', unknown: 'I may not know that well enough to say. Ask me about food, this tea shop, or nearby Yangon.' }, allowedIntents: { SUGGEST_LOCATION: ['market'], SUGGEST_FOOD: ['mohinga', 'laphet', 'tea_snack'], QUEST_HINT: ['market'] } },
  market_seller: { id: 'market_seller', name: 'May', role: 'Market seller', location: 'market', personality: ['energetic', 'practical', 'friendly'], speakingStyle: 'Bright, direct, and brisk.', knowledgeScopes: ['markets', 'yangon', 'landmarks'], questKnowledge: { FIND_LANDMARK: ['shwedagon'] }, discoveryKnowledge: ['shwedagon'], suggestedQuestions: ['What are you selling?', 'Where should I visit?', 'Tell me about this market'], fallbackDialogue: { greeting: 'Welcome! Look around—every stall has something useful or a story to share.', visit: 'Follow the golden skyline toward the Pagoda Gardens for a peaceful change of pace.', yangon: 'Yangon brings busy markets, old shade trees, tea-shop tables, and a golden skyline close together.', quest: 'Look for the golden skyline; it leads toward the Pagoda Gardens.', unknown: 'That is outside my stall knowledge, but I can help with the market or nearby places.' }, allowedIntents: { SUGGEST_LOCATION: ['shwedagon'], QUEST_HINT: ['shwedagon'] } },
  street_local: { id: 'street_local', name: 'Ko Min', role: 'Neighbourhood local', location: 'hotel', personality: ['observant', 'easygoing', 'thoughtful'], speakingStyle: 'Relaxed, curious, and gently humorous.', knowledgeScopes: ['myanmar', 'yangon', 'landmarks'], questKnowledge: { FIND_MARKET: ['market'] }, discoveryKnowledge: [], suggestedQuestions: ['What can I see around here?', 'How should I get around?', 'Tell me about Yangon'], fallbackDialogue: { greeting: 'Good to see you. I like walking these streets before they get too busy.', visit: 'Nearby, you can find the tea shop, the market, and views toward the golden gardens.', yangon: 'Yangon rewards an unhurried walk. Notice the shade trees, street life, and places where neighbours gather.', quest: 'Try asking at the tea shop; Daw Nwe knows which road will take you onward.', unknown: 'I am not certain about that. I can tell you what I know about Yangon and nearby streets.' }, allowedIntents: { SUGGEST_LOCATION: ['tea_shop', 'market'], QUEST_HINT: ['market'] } },
  downtown_bookseller: { id:'downtown_bookseller', name:'Ma Ei', role:'Downtown bookseller', location:'book_arcade', personality:['observant','quiet'], speakingStyle:'Concise and thoughtful.', knowledgeScopes:['downtown','sule','architecture','books'], questKnowledge:{PHOTO_WALK:['sule','heritage_row']}, discoveryKnowledge:['sule','heritage_row'], suggestedQuestions:['Where am I?','What can I see nearby?','How do I get to Sule?'], fallbackDialogue:{greeting:'Welcome. These streets reward anyone who looks above the shop signs.',visit:'Sule is east along the main downtown street; the heritage row is south of here.',food:'The food lanes are farther east, beyond the market arcades.',yangon:'Downtown is dense, walkable, and full of details.',unknown:'I know the downtown streets, books, and nearby landmarks best.'}, allowedIntents:{SUGGEST_LOCATION:['sule','heritage_row'],QUEST_HINT:['sule','heritage_row']} },
  bogyoke_seller: { id:'bogyoke_seller', name:'Thandar', role:'Market seller', location:'bogyoke_market', personality:['practical','bright'], speakingStyle:'Friendly and direct.', knowledgeScopes:['bogyoke-market','souvenirs','chinatown'], questKnowledge:{FOOD_TRAIL:['street_food']}, discoveryKnowledge:['street_food'], suggestedQuestions:['What can I browse?','Where can I get food?','What is nearby?'], fallbackDialogue:{greeting:'Take your time through the arcades; the small details are worth seeing.',food:'For an evening meal, continue east to the food lane.',visit:'The street-food lanes are east; downtown and Sule are west.',unknown:'I can help with this market and the food streets nearby.'}, allowedIntents:{SUGGEST_LOCATION:['street_food'],QUEST_HINT:['street_food']} },
  food_vendor: { id:'food_vendor', name:'Ko Aung', role:'Food vendor', location:'street_food', personality:['busy','good-humoured'], speakingStyle:'Brief, warm, never encyclopedic.', knowledgeScopes:['food','street-food','market_chinatown'], questKnowledge:{FOOD_TRAIL:['street_food','tea_shop']}, discoveryKnowledge:['street_food'], suggestedQuestions:['What should I eat?','Where am I?','Is there somewhere quiet nearby?'], fallbackDialogue:{greeting:'You found the evening food lane. Choose a table when you are ready.',food:'Our configured trail includes noodles here and mohinga at the neighbourhood tea shop.',visit:'For quiet, Kandawgyi is to the south-east; discover its taxi point before riding there.',unknown:'Food and these nearby lanes are what I know best.'}, allowedIntents:{SUGGEST_LOCATION:['kandawgyi_walk'],SUGGEST_FOOD:['shan_noodles','mohinga'],QUEST_HINT:['street_food']} },
  landmark_guide: { id:'landmark_guide', name:'Thiri', role:'Knowledgeable local', location:'shwedagon', personality:['respectful','measured'], speakingStyle:'Careful and concise.', knowledgeScopes:['shwedagon-area','respectful-visiting','viewpoints'], questKnowledge:{PHOTO_WALK:['shwedagon_viewpoint']}, discoveryKnowledge:['shwedagon_viewpoint'], suggestedQuestions:['Where am I?','Where is the photo viewpoint?','What can I see nearby?'], fallbackDialogue:{greeting:'Welcome. Please explore quietly and use the configured viewpoint for photographs.',visit:'The photography viewpoint is south-east of the garden approach.',unknown:'I can help with this area and respectful observation points.'}, allowedIntents:{SUGGEST_LOCATION:['shwedagon_viewpoint'],QUEST_HINT:['shwedagon_viewpoint']} },
  park_visitor: { id:'park_visitor', name:'Mya Mya', role:'Park visitor', location:'garden_bench', personality:['calm','friendly'], speakingStyle:'Relaxed and unhurried.', knowledgeScopes:['kandawgyi','parks','viewpoints'], questKnowledge:{PHOTO_WALK:['lake_viewpoint']}, discoveryKnowledge:['lake_viewpoint'], suggestedQuestions:['Where am I?','What can I see nearby?','Is there somewhere quiet nearby?'], fallbackDialogue:{greeting:'This is a good place to slow down for a while.',visit:'The lake walk is north-west and the sunset deck is east.',food:'The busy food lane is north, beyond the market area.',unknown:'I mostly know this park, its walks, and lake viewpoints.'}, allowedIntents:{SUGGEST_LOCATION:['kandawgyi_walk','lake_viewpoint'],QUEST_HINT:['lake_viewpoint']} },
  taxi_driver: { id:'taxi_driver', name:'U Zaw', role:'Taxi driver', location:'strand_frontage', personality:['helpful','matter-of-fact'], speakingStyle:'Clear directions using configured districts only.', knowledgeScopes:['transport','waterfront','districts'], questKnowledge:{LOCAL_STORIES:['strand_frontage','pansodan_jetty']}, discoveryKnowledge:['strand_frontage'], suggestedQuestions:['How do I get to Shwedagon?','Where am I?','What can I see nearby?'], fallbackDialogue:{greeting:'The Strand road and river are here. I can explain discovered district transfers.',visit:'Downtown is north-west; Shwedagon is inland to the south-west.',unknown:'I only give directions to configured Yangon places.'}, allowedIntents:{SUGGEST_LOCATION:['sule','shwedagon','kandawgyi_walk'],QUEST_HINT:['strand_frontage']} },
};

export const npcForLocation = (locationId: string) => Object.values(AI_NPCS).find(npc => npc.location === locationId);

