export type AINPC = {
  id: string; name: string; role: string; location: string; personality: string[]; speakingStyle: string;
  knowledgeScopes: string[]; questKnowledge: Record<string, string[]>; discoveryKnowledge: string[];
  suggestedQuestions: string[]; fallbackDialogue: Record<string, string>;
  allowedIntents: Record<string, string[]>;
};

export const AI_NPCS: Record<string, AINPC> = {
  tea_shop_owner: { id: 'tea_shop_owner', name: 'Daw Nwe', role: 'Tea shop owner', location: 'tea_shop', personality: ['friendly', 'welcoming', 'interested in local food'], speakingStyle: 'Warm, conversational, and concise.', knowledgeScopes: ['food', 'tea-shops', 'yangon', 'markets'], questKnowledge: { FIND_MARKET: ['market'] }, discoveryKnowledge: ['market'], suggestedQuestions: ['What should I eat?', 'Where should I visit?', 'Tell me about this place'], fallbackDialogue: { greeting: 'Mingalaba. Sit for a moment—there is always room for one more cup.', food: 'Try mohinga: a comforting rice-noodle soup often enjoyed in the morning.', mohinga: 'Mohinga is a fragrant rice-noodle soup, commonly served with fish broth and crisp garnishes.', visit: 'The neighbourhood market is a lively next stop. Follow the road east from the tea shop.', yangon: 'Yangon is best met slowly—through its tea shops, markets, shaded streets, and golden skyline.', quest: 'If you are lost, begin with the market east of here.', unknown: 'I may not know that well enough to say. Ask me about food, this tea shop, or nearby Yangon.' }, allowedIntents: { SUGGEST_LOCATION: ['market'], SUGGEST_FOOD: ['mohinga', 'laphet', 'tea_snack'], QUEST_HINT: ['market'] } },
  market_seller: { id: 'market_seller', name: 'May', role: 'Market seller', location: 'market', personality: ['energetic', 'practical', 'friendly'], speakingStyle: 'Bright, direct, and brisk.', knowledgeScopes: ['markets', 'yangon', 'landmarks'], questKnowledge: { FIND_LANDMARK: ['shwedagon'] }, discoveryKnowledge: ['shwedagon'], suggestedQuestions: ['What are you selling?', 'Where should I visit?', 'Tell me about this market'], fallbackDialogue: { greeting: 'Welcome! Look around—every stall has something useful or a story to share.', visit: 'Follow the golden skyline toward the Pagoda Gardens for a peaceful change of pace.', yangon: 'Yangon brings busy markets, old shade trees, tea-shop tables, and a golden skyline close together.', quest: 'Look for the golden skyline; it leads toward the Pagoda Gardens.', unknown: 'That is outside my stall knowledge, but I can help with the market or nearby places.' }, allowedIntents: { SUGGEST_LOCATION: ['shwedagon'], QUEST_HINT: ['shwedagon'] } },
  street_local: { id: 'street_local', name: 'Ko Min', role: 'Neighbourhood local', location: 'hotel', personality: ['observant', 'easygoing', 'thoughtful'], speakingStyle: 'Relaxed, curious, and gently humorous.', knowledgeScopes: ['myanmar', 'yangon', 'landmarks'], questKnowledge: { FIND_MARKET: ['market'] }, discoveryKnowledge: [], suggestedQuestions: ['What can I see around here?', 'How should I get around?', 'Tell me about Yangon'], fallbackDialogue: { greeting: 'Good to see you. I like walking these streets before they get too busy.', visit: 'Nearby, you can find the tea shop, the market, and views toward the golden gardens.', yangon: 'Yangon rewards an unhurried walk. Notice the shade trees, street life, and places where neighbours gather.', quest: 'Try asking at the tea shop; Daw Nwe knows which road will take you onward.', unknown: 'I am not certain about that. I can tell you what I know about Yangon and nearby streets.' }, allowedIntents: { SUGGEST_LOCATION: ['tea_shop', 'market'], QUEST_HINT: ['market'] } },
};

export const npcForLocation = (locationId: string) => Object.values(AI_NPCS).find(npc => npc.location === locationId);

