import type { GameplayEvent, GameplayEventType, PlayerSave, Vec3 } from '@/lib/types';

export type ObjectiveType='VISIT'|'EAT'|'TALK'|'ACTIVITY'|'PHOTO'|'DISCOVER'|'RETURN'|'LUGGAGE'|'SLEEP'|'TRAVEL';
export type DayOneObjective={id:string;chapterId:'YANGON_DAY_1';title:string;description:string;type:ObjectiveType;requirements:string[];completionEvent:{type:GameplayEventType;targetId:string};reward:{mmk?:number;discoveryId?:string};nextObjectiveId?:string;navigation?:{position:Vec3;mode:'EXACT'|'SEARCH_AREA';nearbyRadius:number}};
const objective=(value:DayOneObjective)=>value;
export const DAY_ONE_OBJECTIVES:DayOneObjective[]=[
 objective({id:'CHECK_IN_GUEST_HOUSE',chapterId:'YANGON_DAY_1',title:'Check into the Guest House',description:'Meet your host and check in.',type:'ACTIVITY',requirements:[],completionEvent:{type:'ACTIVITY_COMPLETED',targetId:'hotel_checkin'},reward:{},nextObjectiveId:'LEAVE_YOUR_BAG',navigation:{position:[-24,0,21],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'LEAVE_YOUR_BAG',chapterId:'YANGON_DAY_1',title:'Leave Your Bag',description:'Leave your travel backpack safely with the Guest House.',type:'LUGGAGE',requirements:['CHECK_IN_GUEST_HOUSE'],completionEvent:{type:'LUGGAGE_STORED',targetId:'guest_house'},reward:{},nextObjectiveId:'VISIT_TEA_SHOP',navigation:{position:[-24,0,21],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'VISIT_TEA_SHOP',chapterId:'YANGON_DAY_1',title:'Visit the Tea Shop',description:'Walk to Morning Star Tea Shop for breakfast.',type:'VISIT',requirements:['LEAVE_YOUR_BAG'],completionEvent:{type:'LOCATION_ENTERED',targetId:'tea_shop'},reward:{},nextObjectiveId:'EAT_BREAKFAST',navigation:{position:[-8,0,7.6],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'EAT_BREAKFAST',chapterId:'YANGON_DAY_1',title:'Eat Breakfast',description:'Order a bowl of mohinga.',type:'EAT',requirements:['VISIT_TEA_SHOP'],completionEvent:{type:'FOOD_EATEN',targetId:'mohinga'},reward:{},nextObjectiveId:'TALK_TO_TEA_SHOP_OWNER',navigation:{position:[-8,0,7.6],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'TALK_TO_TEA_SHOP_OWNER',chapterId:'YANGON_DAY_1',title:'Ask Where to Explore',description:'Ask Daw Nwe where you should explore next.',type:'TALK',requirements:['EAT_BREAKFAST'],completionEvent:{type:'LOCATION_REVEALED',targetId:'market'},reward:{discoveryId:'market_revealed'},nextObjectiveId:'VISIT_MARKET',navigation:{position:[-8,0,7.6],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'VISIT_MARKET',chapterId:'YANGON_DAY_1',title:'Explore the Market',description:'Follow the map and street signs to Lanmadaw Market.',type:'VISIT',requirements:['TALK_TO_TEA_SHOP_OWNER'],completionEvent:{type:'LOCATION_ENTERED',targetId:'market'},reward:{},nextObjectiveId:'EXPLORE_MARKET',navigation:{position:[13,0,10.2],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'EXPLORE_MARKET',chapterId:'YANGON_DAY_1',title:'Explore the Market',description:'Browse the stalls, then ask May what to see in Yangon.',type:'ACTIVITY',requirements:['VISIT_MARKET'],completionEvent:{type:'LOCATION_REVEALED',targetId:'shwedagon'},reward:{discoveryId:'landmark_revealed'},nextObjectiveId:'VISIT_LANDMARK',navigation:{position:[13,0,10.2],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'VISIT_LANDMARK',chapterId:'YANGON_DAY_1',title:'Visit the Golden Pagoda Gardens',description:'Walk toward the golden skyline.',type:'VISIT',requirements:['EXPLORE_MARKET'],completionEvent:{type:'LOCATION_DISCOVERED',targetId:'shwedagon'},reward:{},nextObjectiveId:'PHOTOGRAPH_LANDMARK',navigation:{position:[19,0,-8.8],mode:'EXACT',nearbyRadius:8}}),
 objective({id:'PHOTOGRAPH_LANDMARK',chapterId:'YANGON_DAY_1',title:'Photograph the Landmark',description:'Enter camera mode and frame the golden gardens.',type:'PHOTO',requirements:['VISIT_LANDMARK'],completionEvent:{type:'PHOTO_TAKEN',targetId:'landmark_photo'},reward:{},nextObjectiveId:'FIND_HIDDEN_VIEWPOINT',navigation:{position:[19,0,-8.8],mode:'EXACT',nearbyRadius:10}}),
 objective({id:'FIND_HIDDEN_VIEWPOINT',chapterId:'YANGON_DAY_1',title:'Find the Hidden Viewpoint',description:'Search west of the gardens near the blue lanterns.',type:'DISCOVER',requirements:['PHOTOGRAPH_LANDMARK'],completionEvent:{type:'LOCATION_DISCOVERED',targetId:'viewpoint'},reward:{},nextObjectiveId:'TAKE_VIEWPOINT_PHOTO',navigation:{position:[24,0,17],mode:'SEARCH_AREA',nearbyRadius:8}}),
 objective({id:'TAKE_VIEWPOINT_PHOTO',chapterId:'YANGON_DAY_1',title:'Photograph the View',description:'Capture the view. Sunset earns a special memory.',type:'PHOTO',requirements:['FIND_HIDDEN_VIEWPOINT'],completionEvent:{type:'PHOTO_TAKEN',targetId:'viewpoint_photo'},reward:{},nextObjectiveId:'RETURN_TO_GUEST_HOUSE',navigation:{position:[24,0,17],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'RETURN_TO_GUEST_HOUSE',chapterId:'YANGON_DAY_1',title:'Return to the Guest House',description:'Walk home and end your first day.',type:'RETURN',requirements:['TAKE_VIEWPOINT_PHOTO'],completionEvent:{type:'LOCATION_ENTERED',targetId:'hotel'},reward:{},nextObjectiveId:'END_DAY_AND_SLEEP',navigation:{position:[-24,0,21],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'END_DAY_AND_SLEEP',chapterId:'YANGON_DAY_1',title:'Sleep at the Guest House',description:'End Day 1, then sleep until morning.',type:'SLEEP',requirements:['RETURN_TO_GUEST_HOUSE'],completionEvent:{type:'SLEEP_COMPLETED',targetId:'guest_house'},reward:{},nextObjectiveId:'COLLECT_YOUR_BAG',navigation:{position:[-24,0,21],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'COLLECT_YOUR_BAG',chapterId:'YANGON_DAY_1',title:'Collect Your Bag',description:'Prepare for Bagan by collecting your backpack.',type:'LUGGAGE',requirements:['END_DAY_AND_SLEEP'],completionEvent:{type:'LUGGAGE_COLLECTED',targetId:'guest_house'},reward:{},nextObjectiveId:'GO_TO_BUS_STATION',navigation:{position:[-24,0,21],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'GO_TO_BUS_STATION',chapterId:'YANGON_DAY_1',title:'Go to the Bus Station',description:'Your ticket costs 9,000 MMK. Travel to Yangon Road Ticket Station.',type:'VISIT',requirements:['COLLECT_YOUR_BAG'],completionEvent:{type:'LOCATION_ENTERED',targetId:'bus'},reward:{},nextObjectiveId:'BUY_BAGAN_TICKET',navigation:{position:[-25,0,-11.8],mode:'EXACT',nearbyRadius:7}}),
 objective({id:'BUY_BAGAN_TICKET',chapterId:'YANGON_DAY_1',title:'Buy Your Bagan Ticket',description:'Review the journey and buy one server-timed bus ticket.',type:'TRAVEL',requirements:['GO_TO_BUS_STATION'],completionEvent:{type:'TRAVEL_STARTED',targetId:'yangon_bagan_bus'},reward:{},navigation:{position:[-25,0,-11.8],mode:'EXACT',nearbyRadius:7}}),
];
export const objectiveById=(id:string)=>DAY_ONE_OBJECTIVES.find(x=>x.id===id);
export function consumeQuestEvent(player:PlayerSave,event:GameplayEvent):PlayerSave{
 const current=objectiveById(player.activeObjectiveId); if(!current||current.completionEvent.type!==event.type||current.completionEvent.targetId!==event.targetId)return {...player,gameplayEvents:[...player.gameplayEvents.slice(-99),event]};
 const completed=[...new Set([...player.completedObjectives,current.id])];
 return {...player,completedObjectives:completed,activeObjectiveId:current.nextObjectiveId??current.id,gameplayEvents:[...player.gameplayEvents.slice(-99),event],discoveries:current.reward.discoveryId?[...new Set([...player.discoveries,current.reward.discoveryId])]:player.discoveries,mmk:player.mmk+(current.reward.mmk??0)};
}
