'use client';

import { useCallback, useEffect, useState } from 'react';
import { BUS_ROUTE, QUESTS, SLEEP_OPTIONS, SPOTS } from '@/content/game';
import { api, useGame } from '@/store/game';
import { attractionStatus, formatGameTime, journeyObjective, progress } from '@/lib/rules';
import { DEFAULT_SETTINGS, loadSettings, saveSettings, type GameSettings } from '@/lib/settings';
import type { PlayerSave } from '@/lib/types';
import { ACTIVITIES, locationById } from '@/content/locations';
import { executeInteraction } from '@/components/game/InputController';
import SleepExperience from '@/components/game/SleepExperience';
import Wardrobe from '@/components/avatar/Wardrobe';
import { AVATAR_ITEMS } from '@/content/avatar';
import { objectiveById } from '@/content/day-one';

const fmt = (ms: number) => { const s = Math.max(0, Math.ceil(ms / 1000)); return `${String(Math.floor(s / 3600)).padStart(2, '0')}:${String(Math.floor(s % 3600 / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`; };
const areaName = (p: [number, number, number]) => p[2] < -7 ? (p[0] > 7 ? 'Golden Pagoda District' : 'Station Quarter') : p[0] > 7 ? 'Lanmadaw Market' : p[0] < -14 ? 'Tamarind Quarter' : 'Downtown Crossroads';

export default function Overlay() {
  const { player, panel, activeInteractionTarget, locationId, transitioning, cameraMode, error, setPanel, setPlayer, setLocation, setTransitioning, setCameraMode, setNotice, setError } = useGame();
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const i = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(i); }, []);
  const act = useCallback(async (action: string, data: Record<string, unknown> = {}) => { try { setError(null); const p = await api(action, data); setPlayer(p); return p; } catch (e) { setError(e instanceof Error ? e.message : 'Network error'); } }, [setError, setPlayer]);
  const transitionLocation = useCallback((id:string|null) => { setTransitioning(true); setTimeout(() => { setPanel(null); setLocation(id); setTimeout(() => setTransitioning(false), 180); }, 260); }, [setLocation, setPanel, setTransitioning]);
  const takePhoto = useCallback(async () => { const state = useGame.getState(), currentPlayer = state.player; if (!currentPlayer) return; const target = currentPlayer.activeObjectiveId === 'PHOTOGRAPH_LANDMARK' ? 'landmark_photo' : currentPlayer.activeObjectiveId === 'TAKE_VIEWPOINT_PHOTO' ? 'viewpoint_photo' : ''; if(!target){setNotice('No photo challenge is active here.');return} const fresh = !currentPlayer.photos.includes(target); const p = await act('photo', { target, facingScore: 1 }); if (p) setNotice(fresh ? 'PHOTO CHALLENGE COMPLETE · +1,500 MMK · Journal updated' : 'Photograph saved · challenge already rewarded'); }, [act, setNotice]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.repeat) return; const state = useGame.getState(); if (e.code === 'Space' && state.cameraMode) { e.preventDefault(); void takePhoto(); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [takePhoto]);
  if (!player) return null;
  if (player.destination === 'BAGAN') return <Completion player={player}/>;
  if (player.majorState === 'SLEEPING' && player.activeAction) return <SleepExperience action={player.activeAction} energy={player.energy} onVerify={() => api().then(setPlayer)} onDevComplete={async () => { await api('dev', { target: 'completeTimer' }).then(setPlayer); await api().then(setPlayer); }}/>;
  if (player.lastSleepCompletedAt && typeof window !== 'undefined' && sessionStorage.getItem('wake-seen') !== player.lastSleepCompletedAt) return <WakeExperience player={player} onContinue={() => { sessionStorage.setItem('wake-seen', player.lastSleepCompletedAt!); setLocation('hotel'); setTransitioning(true); setTimeout(() => setTransitioning(false), 500); }}/>
  if (player.majorState !== 'EXPLORING' && player.activeAction) return <TimerScreen now={now} onRefresh={() => void api().then(setPlayer).catch(e => setError(e.message))} onPanel={() => setPanel('journal')}/>;
  if(locationId)return <>{cameraMode&&<div className="location-camera"><div className="camera-instruction">VIRTUAL CAMERA · SPACE CAPTURE · C CANCEL</div><div className="focus-frame"><i/><i/><i/><i/></div><button aria-label="Take photograph" className="shutter" onClick={()=>void takePhoto()}>●</button></div>}<LocationExperience id={locationId} act={act} leave={async()=>{setTransitioning(true);const next=await act('leaveLocation');if(next){setLocation(null);setTimeout(()=>setTransitioning(false),480)}else setTransitioning(false)}}/>{panel&&<Panel type={panel} close={()=>setPanel(null)} act={act}/>} {error&&<Toast text={error} bad onClose={()=>setError(null)}/>}<Notice/>{transitioning&&<div className="location-fade"/>}</>;
  const spot = activeInteractionTarget, pct = progress(player), objective = journeyObjective(player);
  const closed = spot?.type === 'attraction' && attractionStatus(player.gameMinutes) === 'CLOSED';
  return <><div className={`hud ${cameraMode ? 'camera-hud' : ''}`}><header><div><small>DAY {player.day} · {areaName(player.position).toUpperCase()}</small><strong>{formatGameTime(player.gameMinutes)}</strong></div><div className="brand">EXPLORE <b>MYANMAR</b></div><div className="money">{player.mmk.toLocaleString()} <small>MMK</small></div></header>{!cameraMode && <aside><label>ENERGY <b>{Math.round(player.energy)}</b></label><div className="bar"><i style={{ width: `${player.energy}%` }}/></div><p>{pct}% Yangon documented</p></aside>}<div className="objective">{cameraMode ? 'CAMERA · Compose with mouse · SPACE capture · C exit' : <><b>{objective.title.toUpperCase()}</b> · {objective.detail}<ObjectiveDirection player={player}/></>}</div>{spot && !panel && !cameraMode && <button className="prompt" onClick={() => executeInteraction(spot)}><kbd>E</kbd> {spot.prompt}<small>{spot.label}{closed ? ' · CLOSED · Opens at 06:00' : ''}</small></button>}{cameraMode && <><div className="focus-frame"><i/><i/><i/><i/></div><button aria-label="Take photograph" className="shutter" onClick={() => void takePhoto()}>●</button></>}<nav><button onClick={() => setPanel('map')}>M · Map</button><button onClick={() => setPanel('journal')}>J · Journal</button><button onClick={() => setPanel('wardrobe')}>Wardrobe</button><button onClick={() => setPanel('profile')}>Profile</button><button onClick={() => setPanel('menu')}>⚙</button></nav><div className="tutorial">WASD move · Shift jog · Drag orbit · Wheel zoom · E interact · C camera</div></div>{panel && <Panel type={panel} close={() => setPanel(null)} act={act}/>} {error && <Toast text={error} bad onClose={() => setError(null)}/>}<Notice/>{transitioning&&<div className="location-fade"/>}</>;
}

function LocationExperience({id,act,leave}:{id:string;act:(a:string,d?:Record<string,unknown>)=>Promise<PlayerSave|undefined>;leave:()=>Promise<void>}){
 const location=locationById(id)!;const player=useGame(s=>s.player)!;const setPanel=useGame(s=>s.setPanel);const setNotice=useGame(s=>s.setNotice);
 const [view,setView]=useState<'main'|'food'|'shop'|'talk'|'result'>('main'),[busy,setBusy]=useState(false),[dialogue,setDialogue]=useState('Welcome. Take a seat whenever you are ready.'),[result,setResult]=useState<{name:string;cost:number;energy:number;minutes:number;fresh:boolean}|null>(null);
 useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.code!=='Escape'||event.repeat)return;event.preventDefault();if(view==='main')void leave();else setView('main')};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[leave,view]);
 const run=async(activityId:string)=>{const a=ACTIVITIES.find(x=>x.id===activityId)!;const first=!!a.discoveryId&&!player.discoveries.includes(a.discoveryId);const next=await act('activity',{target:activityId,requestId:crypto.randomUUID()});if(next)setNotice(`${a.name.toUpperCase()} · +${a.gameMinutes} minutes${first?' · NEW DISCOVERY · Added to Journal':''}`);return next};
 const order=async(activityId:string)=>{if(busy)return;const food=ACTIVITIES.find(x=>x.id===activityId)!;setBusy(true);const fresh=!player.foods.includes(food.foodId!);try{const next=await act('orderFood',{foodId:food.foodId,requestId:crypto.randomUUID()});if(next){setResult({name:food.name,cost:food.mmkCost??0,energy:Math.min(food.energyRestore??0,100-player.energy),minutes:food.gameMinutes,fresh});setView('result')}}finally{setBusy(false)}};
 const action=(name:string)=>{if(name==='LEAVE')void leave();else if(name==='ORDER_FOOD')setView('food');else if(name==='BUY_SOUVENIR')setView('shop');else if(name==='TALK'||name==='ASK_ABOUT_YANGON')setView('talk');else if(name==='SLEEP')setPanel('sleep');else if(name==='VIEW_JOURNAL')void run('hotel_review_journal').then(()=>setPanel('journal'));else if(name==='BUY_TICKET'||name==='VIEW_DESTINATIONS')setPanel('travel');else if(name==='PHOTOGRAPH')useGame.getState().setCameraMode(true);else {const map:Record<string,string>={BROWSE:'market_browse',LOOK_AROUND:id==='tea_shop'?'tea_culture':id==='market'?'market_observe':'landmark_observe',REST:player.discoveries.includes('hotel_checked_in')?'hotel_rest':'hotel_checkin',VISIT:'landmark_visit',LEARN:'landmark_learn'};if(map[name])void run(map[name]);}};
 const foods=ACTIVITIES.filter(a=>a.locationId==='tea_shop'&&a.foodId),shop=ACTIVITIES.filter(a=>a.locationId==='market'&&a.inventoryItem);
 const topic=async(kind:'recommend'|'culture'|'visit')=>{if(!player.discoveries.includes('tea_owner_met'))await run('meet_tea_owner');if(kind==='recommend')setDialogue('For breakfast, I recommend the mohinga. It is warm and filling.');if(kind==='culture')setDialogue('Tea shops are places to pause, share food, and catch up with neighbours.');if(kind==='visit'){if(!player.discoveries.includes('market_revealed'))await run('market_recommendation');setDialogue('Walk east to Lanmadaw Market. Follow the red awnings—I have marked the area on your map.')}};
 return <div className="location-ui"><div className="location-card"><div className="eyebrow">{location.type.replace('_',' ')} · YANGON</div><h1>{location.name}</h1><p>{location.description}</p>{id==='hotel'&&player.dayOneCompleted&&<DayOneSummary player={player}/>}
 {view==='main'&&<><small className="question">WHAT WOULD YOU LIKE TO DO?</small>{id==='hotel'&&player.activeObjectiveId==='RETURN_TO_GUEST_HOUSE'&&!player.dayOneCompleted&&<button className="primary" onClick={()=>void act('completeDay').then(p=>p&&setNotice('DAY 1 COMPLETE · Summary ready'))}>END THE DAY</button>}<div className="location-actions">{location.availableActions.filter(a=>a!=='ASK_ABOUT_YANGON').map(a=><button key={a} className={a==='LEAVE'?'leave':''} onClick={()=>action(a)}>{a==='REST'&&!player.discoveries.includes('hotel_checked_in')?'CHECK IN':a.replaceAll('_',' ')}</button>)}</div></>}
 {view==='food'&&<><h2>Order Food</h2><p className="menu-balance">{player.mmk.toLocaleString()} MMK · {Math.round(player.energy)} ENERGY</p>{foods.map(a=>{const disabled=busy||player.mmk<(a.mmkCost??0)||player.energy>=100;return <div className="food-card" key={a.id}><h3>{a.name}</h3><p>{a.description}</p><div><b>{a.mmkCost?.toLocaleString()} MMK</b><span>+{a.energyRestore} Energy · {a.gameMinutes} game minutes</span></div><button disabled={disabled} onClick={()=>void order(a.id)}>{busy?'ORDERING…':player.mmk<(a.mmkCost??0)?'NOT ENOUGH MMK':player.energy>=100?'ENERGY FULL':'ORDER'}</button></div>})}<button className="back-choice" onClick={()=>setView('main')}>← Back</button></>}
 {view==='result'&&result&&<div className="eating-result"><div className="eyebrow">ORDERED</div><h2>{result.name}</h2><div className="eating-cup">♨</div><p>Breakfast is served. Time passes in a quiet, compressed moment.</p><strong>-{result.cost.toLocaleString()} MMK · +{result.energy} Energy · +{result.minutes} minutes</strong>{result.fresh&&<p className="new-discovery">✦ NEW FOOD DISCOVERED<br/><b>{result.name}</b><br/>Added to Journal</p>}<button className="back-choice" onClick={()=>setView('main')}>Continue</button></div>}
 {view==='talk'&&id==='tea_shop'&&<><h2>Daw Nwe, owner</h2><p className="owner-reply">“{dialogue}”</p><button className="dialogue-option" onClick={()=>void topic('recommend')}>What do you recommend?</button><button className="dialogue-option" onClick={()=>void topic('culture')}>Tell me about tea shops</button><button className="dialogue-option" onClick={()=>void topic('visit')}>Where should I explore?</button><button className="back-choice" onClick={()=>setView('main')}>Goodbye</button></>}
 {view==='talk'&&id==='market'&&<><h2>May, market seller</h2><p className="owner-reply">“{dialogue}”</p><button className="dialogue-option" onClick={async()=>{if(!player.discoveries.includes('market_seller_met'))await run('meet_market_seller');if(!player.discoveries.includes('landmark_revealed'))await run('landmark_recommendation');setDialogue('Follow the golden skyline south. The Pagoda Gardens are peaceful in the afternoon.')}}>What should I see in Yangon?</button><button className="dialogue-option" onClick={()=>setDialogue('Postcards, notebooks, keepsakes—and one sturdy traveler cap.')}>What are you selling?</button><button className="dialogue-option" onClick={()=>setDialogue('These fictional neighbourhood stalls bring food, colour, and conversation together.')}>Tell me about this market</button><button className="back-choice" onClick={()=>setView('main')}>Goodbye</button></>} {view==='talk'&&id!=='tea_shop'&&id!=='market'&&<><h2>Local guide</h2><p>“A quieter viewpoint lies west of here, near the blue lanterns.”</p><button className="back-choice" onClick={()=>setView('main')}>Thank you · Back</button></>}
 {view==='shop'&&<><h2>Market Keepsakes & Clothing</h2>{AVATAR_ITEMS.filter(x=>x.unlockType==='MARKET').map(item=><button className="choice dark" key={item.id} disabled={player.avatarInventory.includes(item.id)} onClick={async()=>{const next=await act('avatarBuy',{target:item.id,requestId:crypto.randomUUID()});if(next)setNotice(`NEW ITEM · ${item.name} · Open Wardrobe to equip`)}}><span><b>{item.name}</b><small>{player.avatarInventory.includes(item.id)?'OWNED':'Cosmetic only'}</small></span><strong>{item.price.toLocaleString()} MMK</strong></button>)}{shop.map(a=><button className="choice dark" key={a.id} onClick={()=>void run(a.id)}><span><b>{a.name}</b><small>{a.description}</small></span><strong>{a.mmkCost?.toLocaleString()} MMK</strong></button>)}<button className="back-choice" onClick={()=>setView('main')}>← Back</button></>}
 </div><div className="location-status"><span>OBJECTIVE · {objectiveById(player.activeObjectiveId)?.title}</span> DAY {player.day} · {formatGameTime(player.gameMinutes)} <b>{player.mmk.toLocaleString()} MMK</b> <b>{Math.round(player.energy)} ENERGY</b></div></div>
}
function ObjectiveDirection({player}:{player:PlayerSave}){const objective=objectiveById(player.activeObjectiveId);if(!objective?.navigation)return null;const [x,,z]=objective.navigation.position,dx=x-player.position[0],dz=z-player.position[2],distance=Math.round(Math.hypot(dx,dz));const angle=Math.atan2(dx,-dz);const arrows=['↑','↗','→','↘','↓','↙','←','↖'];const arrow=arrows[(Math.round(angle/(Math.PI/4))+8)%8];if(distance<=objective.navigation.nearbyRadius)return <span className="objective-direction">{objective.navigation.mode==='SEARCH_AREA'?'Search area nearby':'Destination nearby'}</span>;return <span className="objective-direction">{objective.navigation.mode==='SEARCH_AREA'?'Approx. ':''}{arrow} {distance}m</span>}
function DayOneSummary({player}:{player:PlayerSave}){const places=new Set(player.discoveries.filter(x=>x.startsWith('place:')||['shwedagon','viewpoint'].includes(x))).size,spent=Math.max(0,player.dayOneStartingMMK-player.mmk);return <div className="day-summary"><div className="eyebrow">DAY 1 — YANGON</div><h2>Your day in the city</h2><div className="stats"><b>{places}<small>PLACES</small></b><b>{player.foods.length}<small>FOODS</small></b><b>{player.photos.length}<small>PHOTOS</small></b><b>{player.talkedTo.length}<small>PEOPLE</small></b><b>{spent.toLocaleString()}<small>MMK SPENT</small></b><b>{player.discoveries.length}<small>JOURNAL ENTRIES</small></b></div><p>Breakfast at Tea Shop · Explored Market · Visited Landmark · Found Hidden Viewpoint</p></div>}
function Notice() { const { notice, setNotice } = useGame(); useEffect(() => { if (notice) { const t = setTimeout(() => setNotice(null), 4200); return () => clearTimeout(t); } }, [notice, setNotice]); return notice ? <Toast text={notice} onClose={() => setNotice(null)}/> : null; }
function Toast({ text, bad, onClose }: { text: string; bad?: boolean; onClose: () => void }) { return <button className={`toast ${bad ? 'bad' : ''}`} onClick={onClose}>{bad ? '! ' : '✦ '}{text}</button>; }

function Panel({ type, close, act }: { type: string; close: () => void; act: (a: string, d?: Record<string, unknown>) => Promise<PlayerSave | undefined> }) {
  const p = useGame(s => s.player)!;
  return <div className="modal-back"><section className="panel"><button className="close" onClick={close}>×</button>{type === 'journal' && <Journal p={p}/>} {type === 'map' && <MapPanel p={p}/>} {type === 'profile' && <Profile p={p}/>} {type === 'sleep' && <><div className="eyebrow">GOLDEN TAMARIND GUESTHOUSE</div><h2>Rest for a while</h2><p>Sleep is timed by the server. You may safely close the browser and return later.</p>{SLEEP_OPTIONS.map(o => <button className="choice" key={o.hours} onClick={() => void act('sleep', { value: o.hours })}><span><b>{o.hours} game hours</b><small>Restore up to {o.recovery} energy</small></span><strong>≈ {o.hours * 6} min</strong></button>)}</>} {type === 'travel' && <><div className="eyebrow">YANGON ROAD TICKET STATION</div><h2>Yangon → Bagan</h2><p>Express bus · 11 game hours · server-timed {BUS_ROUTE.realMinutes}-minute journey.</p><p>{p.baganUnlocked ? 'Your Yangon field notes qualify you for onward travel.' : 'Document 30%, including a food, photograph, and landmark.'}</p><button className="primary" disabled={!p.baganUnlocked || p.mmk < BUS_ROUTE.price} onClick={() => void act('travel')}>Buy ticket · {BUS_ROUTE.price.toLocaleString()} MMK</button></>} {type === 'wardrobe' && <Wardrobe player={p} onEquip={async id=>{await act('avatarEquip',{target:id})}}/>} {type === 'menu' && <Settings act={act}/>}</section></div>;
}

function Profile({ p }: { p: PlayerSave }) { const identity=useGame(s=>s.identity); const reset=useGame(s=>s.reset); const registered=identity?.type==='REGISTERED'; async function leave(){await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent:'logout'})});reset();location.assign('/');} return <><div className="eyebrow">TRAVELER PROFILE</div><h2>{identity?.displayName??'Guest Traveler'}</h2><p><b>{registered?'Registered Player':'Guest Traveler'}</b></p><div className="stats"><b>{new Date(identity?.journeyStartedAt??Date.now()).toLocaleDateString()}<small>JOURNEY START</small></b><b>{p.destination}<small>CURRENT DESTINATION</small></b><b>{progress(p)}%<small>YANGON</small></b><b>{p.discoveries.length}<small>DISCOVERIES</small></b><b>{p.photos.length}<small>PHOTOS</small></b><b>{p.mmk.toLocaleString()}<small>MMK</small></b></div>{registered?<button className="primary profile-action" onClick={()=>void leave()}>Log Out</button>:<><p>Your guest journey is stored in this browser session. Create an account to secure it.</p><button className="primary profile-action" onClick={()=>location.assign('/?register=1')}>Save My Journey</button></>}</>; }

const JOURNAL_TABS = ['OVERVIEW', 'DESTINATIONS', 'DISCOVERIES', 'FOOD', 'PEOPLE', 'PHOTOS', 'STORIES', 'JOURNEY'] as const;
function Journal({ p }: { p: PlayerSave }) { const [tab, setTab] = useState<(typeof JOURNAL_TABS)[number]>('OVERVIEW'); const cards = tab === 'FOOD' ? p.foods : tab === 'PEOPLE' ? p.talkedTo : tab === 'PHOTOS' ? p.photos : p.discoveries; return <><div className="eyebrow">TRAVEL JOURNAL · YANGON</div><h2>My Journey</h2><div className="journal-tabs">{JOURNAL_TABS.map(x => <button className={tab === x ? 'active' : ''} onClick={() => setTab(x)} key={x}>{x}</button>)}</div>{tab === 'OVERVIEW' && <><div className="stats"><b>{progress(p)}%<small>COMPLETE</small></b><b>{p.discoveries.filter(x => !x.startsWith('food:')).length}<small>LANDMARKS & PLACES</small></b><b>{p.foods.length}/3<small>FOODS</small></b><b>{p.talkedTo.length}/5<small>PEOPLE</small></b><b>{p.photos.length}/3<small>PHOTO CHALLENGES</small></b><b>{p.completedQuests.length}/3<small>ACTIVITIES</small></b></div><h3>Active stories</h3>{QUESTS.map(q => <p className="journal-row" key={q.id}><span>{p.completedQuests.includes(q.id) ? '✓' : '○'}</span><b>{q.name}</b> · {q.text}</p>)}</>}{tab === 'DESTINATIONS' && <div className="card-grid"><article><small>ACTIVE DESTINATION</small><h3>Yangon</h3><p>Warm streets, local food and a golden skyline.</p></article><article className={p.baganUnlocked ? '' : 'locked'}><small>{p.baganUnlocked ? 'ROUTE UNLOCKED' : 'LOCKED'}</small><h3>Bagan</h3><p>Onward travel finale — world coming later.</p></article></div>}{tab === 'JOURNEY' || tab === 'STORIES' ? <div className="timeline">{[...p.timeline].reverse().map((x, i) => <p key={i}><span>DAY {x.day}</span>{x.text}</p>)}</div> : tab !== 'OVERVIEW' && tab !== 'DESTINATIONS' && <div className="card-grid">{cards.length ? cards.map(x => <article key={x}><small>JOURNAL ENTRY</small><h3>{x.replaceAll('_', ' ')}</h3><p>Recorded in Yangon.</p></article>) : <p>Explore Yangon to add entries here.</p>}</div>}</>; }

function MapPanel({ p }: { p: PlayerSave }) { const known = (id: string) => id === 'hotel' || id === 'tea_shop' || id === 'bus' || id==='shwedagon'&&p.discoveries.includes('landmark_recommended') || p.discoveries.includes(id); const left = `${50 + p.position[0] * 1.25}%`, top = `${50 + p.position[2] * 1.25}%`; return <><div className="eyebrow">FIELD MAP · PLAYABLE DISTRICT</div><h2>Yangon</h2><div className="map"><div className="map-road vertical"/><div className="map-road horizontal"/>{p.discoveries.includes('viewpoint_revealed')&&!p.discoveries.includes('viewpoint')&&<i className="search-area" style={{left:'76%',top:'66%'}} title="Approximate search area">SEARCH AREA</i>}{SPOTS.filter(s => s.id !== 'viewpoint' || p.discoveries.includes('viewpoint')).map(s => <i key={s.id} className={known(s.id) ? 'known' : ''} style={{ left: `${50 + s.position[0] * 1.25}%`, top: `${50 + s.position[2] * 1.25}%` }} title={known(s.id) ? s.name : 'Undiscovered'}>{known(s.id) ? '●' : '?'}</i>)}<em className="you" style={{ left, top }}>YOU</em></div><div className="map-legend"><span>● Known place</span><span>? Undiscovered</span><span>◆ Main road</span></div><p>Yangon <b>ACTIVE</b> · Bagan <b>{p.baganUnlocked ? 'ROUTE UNLOCKED' : 'LOCKED'}</b></p></>; }


function Settings({ act }: { act: (a: string, d?: Record<string, unknown>) => Promise<PlayerSave | undefined> }) {
 const [settings,setSettings]=useState<GameSettings>(()=>typeof window==='undefined'?DEFAULT_SETTINGS:loadSettings()),[confirm,setConfirm]=useState<'position'|'journey'|null>(null),[busy,setBusy]=useState(false);const player=useGame(s=>s.player)!;const requestRecovery=useGame(s=>s.requestRecovery),setPanel=useGame(s=>s.setPanel),setPlayer=useGame(s=>s.setPlayer),setError=useGame(s=>s.setError),diagnostics=useGame(s=>s.worldDiagnostics),forceDevFall=useGame(s=>s.forceDevFall);
 function update<K extends keyof GameSettings>(key:K,value:GameSettings[K]){const next={...settings,[key]:value};setSettings(next);saveSettings(next)}
 function resetPosition(){setPlayer({...player,position:[...player.lastSafePosition]});useGame.getState().setLocation(null);requestRecovery();setPanel(null);setConfirm(null)}
 async function newJourney(){setBusy(true);setError(null);try{const response=await fetch('/api/player/reset',{method:'POST'}),json=await response.json();if(!response.ok)throw new Error(json.error);setPlayer(json.player);useGame.getState().setLocation(null);requestRecovery();setPanel(null);useGame.getState().setNotice('New journey started safely in Yangon.');}catch(e){setError(e instanceof Error?e.message:'Journey reset failed')}finally{setBusy(false)}}
 if(confirm==='position')return <div className="confirm"><div className="eyebrow">PLAYER RECOVERY</div><h2>Return to a safe location?</h2><p>Your MMK, energy, discoveries, quests, journal, inventory, account, and destination progress will be preserved.</p><div className="confirm-actions"><button onClick={()=>setConfirm(null)}>Cancel</button><button className="primary" onClick={resetPosition}>Reset Position</button></div></div>;
 if(confirm==='journey')return <div className="confirm destructive"><div className="eyebrow">JOURNEY RESET</div><h2>START A NEW JOURNEY?</h2><p>This will reset your current Explore Myanmar journey, including progress, MMK, discoveries, quests and journal.</p><p><b>Your account will NOT be deleted.</b></p><div className="confirm-actions"><button disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button disabled={busy} className="danger" onClick={()=>void newJourney()}>{busy?'Resetting…':'Start New Journey'}</button></div></div>;
 return <><div className="eyebrow">ESC MENU · FIELD KIT</div><h2>Settings</h2><button className="recovery-action" disabled={player.majorState!=='EXPLORING'} onClick={()=>setConfirm('position')}><b>Reset Position</b><small>{player.majorState==='EXPLORING'?'Return to your last safe checkpoint without losing progress.':'Available while exploring.'}</small></button><h3>Graphics quality</h3><div className="segmented">{(['LOW','MEDIUM','HIGH'] as const).map(q=><button className={settings.graphics===q?'active':''} key={q} onClick={()=>update('graphics',q)}>{q}</button>)}</div><p className="hint">Graphics changes fully apply after refresh.</p><h3>Audio</h3>{(['master','music','ambience','sfx'] as const).map(k=><label className="slider" key={k}><span>{k.toUpperCase()} <b>{settings[k]}%</b></span><input type="range" min="0" max="100" value={settings[k]} onChange={e=>update(k,Number(e.target.value))}/></label>)}<h3>Controls</h3><p>WASD move · Shift jog · Mouse drag orbit · Wheel zoom<br/>E interact · C camera · M map · J journal · Esc menu</p><h3>Journey</h3><button className="journey-action" onClick={()=>setConfirm('journey')}>Start New Journey</button>{process.env.NODE_ENV!=='production'&&<><h3>Developer Field Kit</h3><div className="dev"><button onClick={()=>void act('dev',{target:'mmk',value:10000})}>+10k MMK</button><button onClick={()=>void act('dev',{target:'energy',value:100})}>Full energy</button><button onClick={()=>void act('dev',{target:'unlock'})}>Unlock Bagan</button><button onClick={()=>void act('dev',{target:'time',value:1080})}>Sunset</button><button onClick={()=>void act('dev',{target:'completeTimer'})}>Complete timer</button><button onClick={forceDevFall}>Force below killY</button></div>{diagnostics&&<pre className="diagnostics">player XYZ {diagnostics.position.map(n=>n.toFixed(2)).join(', ')}{`\n`}last safe XYZ {diagnostics.lastSafe.map(n=>n.toFixed(2)).join(', ')}{`\n`}checkpoint {diagnostics.checkpoint}{`\n`}bounds X -34..34 · Z -34..34 · killY -8{`\n`}out of bounds {String(diagnostics.outOfBounds)} · grounded {String(diagnostics.grounded)}</pre>}</>}</>;
}

function TimerScreen({ now, onRefresh, onPanel }: { now: number; onRefresh: () => void; onPanel: () => void }) { const p = useGame(s => s.player)!; const a = p.activeAction!; const remain = new Date(a.completesAt).getTime() - now; useEffect(() => { if (remain <= 0) { const t = setTimeout(onRefresh, 800); return () => clearTimeout(t); } }, [remain, onRefresh]); const travel = p.majorState === 'TRAVELLING'; return <main className={`timer-screen ${travel ? 'travel-bg' : 'sleep-bg'}`}><div className="timer-card"><div className="eyebrow">{travel ? 'ON THE ROAD' : 'RESTING IN YANGON'}</div><h1>{travel ? 'Yangon → Bagan' : 'Sleeping'}</h1><div className="countdown">{fmt(remain)}</div><p>{travel ? 'Express Bus · 11 game hours' : `Golden Tamarind Guesthouse · ${a.energyRecovery} energy recovery`}</p><div className="progress"><i style={{ width: `${Math.min(100, 100 * (now - new Date(a.startedAt).getTime()) / (new Date(a.completesAt).getTime() - new Date(a.startedAt).getTime()))}%` }}/></div><button onClick={onPanel}>Open journal</button><button onClick={onRefresh}>Verify with server</button></div></main>; }
function WakeExperience({ player, onContinue }: { player: PlayerSave; onContinue: () => void }) { return <main className="wake-experience"><div className="morning-sun"/><section><div className="eyebrow">A NEW DAY BEGINS</div><h1>Good Morning</h1><h2>Yangon · {formatGameTime(player.gameMinutes)}</h2><div className="wake-energy"><span>ENERGY RESTORED</span><strong>{Math.round(player.energy)} / 100</strong></div><p>Morning light reaches the Golden Tamarind Guesthouse. Your journey is ready when you are.</p><button onClick={onContinue}>Continue Journey</button></section></main> }
function Completion({ player }: { player: PlayerSave }) { return <main className="completion"><div><div className="eyebrow">YOUR JOURNEY CONTINUES</div><h1>Welcome to Bagan</h1><p>You’ve completed the Explore Myanmar alpha journey. The destination world is not part of this release.</p><strong>COMING SOON</strong><div className="stats"><b>{progress(player)}%<small>YANGON</small></b><b>{player.discoveries.length}<small>DISCOVERIES</small></b><b>{player.photos.length}<small>PHOTOS</small></b><b>{player.mmk.toLocaleString()}<small>MMK LEFT</small></b></div></div></main>; }
